//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a d498282f-ffd9-4649-a4bd-4769ae7b7f07.
        /// </summary>
        public static string CNH_TYPE_A {
            get {
                return ResourceManager.GetString("CNH_TYPE_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a b91d2876-0df4-4373-92b6-9e1bde27d66b.
        /// </summary>
        public static string STATUSDELIVERYORDER_ACCEPT {
            get {
                return ResourceManager.GetString("STATUSDELIVERYORDER_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a eadc1d7d-ffdb-45c0-aa12-c03e4a4e86b8.
        /// </summary>
        public static string STATUSDELIVERYORDER_CONCLUDED {
            get {
                return ResourceManager.GetString("STATUSDELIVERYORDER_CONCLUDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELIVERYORDER.
        /// </summary>
        public static string TABLE_NAME_DELIVERYORDER {
            get {
                return ResourceManager.GetString("TABLE_NAME_DELIVERYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MOTORCYCLE.
        /// </summary>
        public static string TABLE_NAME_MOTORCYCLE {
            get {
                return ResourceManager.GetString("TABLE_NAME_MOTORCYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MOTORCYCLERENTAL.
        /// </summary>
        public static string TABLE_NAME_MOTORCYCLERENTAL {
            get {
                return ResourceManager.GetString("TABLE_NAME_MOTORCYCLERENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STATUSDELIVERYORDER.
        /// </summary>
        public static string TABLE_NAME_STATUSDELIVERYORDER {
            get {
                return ResourceManager.GetString("TABLE_NAME_STATUSDELIVERYORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USERSYSTEM.
        /// </summary>
        public static string TABLE_NAME_USERSYSTEM {
            get {
                return ResourceManager.GetString("TABLE_NAME_USERSYSTEM", resourceCulture);
            }
        }
    }
}
